version: "3.7"

services:
  # The actual database
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/db-data:/data/db"
      - "./mongodb/backups:/backups"

  # Auxiliary container to connect to db and initialize data
  initdb:
    build: ./mongodb
    links:
      - mongodb
    command:
      - /app/scripts/init_db.sh

  # The REST API
  nodeapi: 
    build: ./node_api
    ports: 
      - "8080:8080"
    links:
      - mongodb
    command:
      - /app/server.js

  # Frontend
  #frontend:
  #  build: ./react_frontend
  #  ports:
  #    - "3000:3000"
  #  links: 
  #    - nodeapi
