version: "3.7"

services:
  # The actual database
  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/db-data:/data/db"
      - "./mongodb/backups:/backups"

  # Auxiliary container to connect to db and initialize data
  initdb:
    build: ./mongodb
    links:
      - mongodb
    command:
      - /app/scripts/init_db.sh